# Generated by Django 5.0.3 on 2024-03-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
