# Generated by Django 5.0.3 on 2024-03-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma_app', '0002_alter_medicament_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='date_exp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
