# Generated by Django 5.0.4 on 2024-05-12 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharma_app', '0005_alter_medicament_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicament',
            options={'permissions': [('publish_medicament', 'Can publish a Medecine'), ('sell_medicament', 'Can sell a Medecine')]},
        ),
    ]
