# Generated by Django 5.0.4 on 2024-05-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma_app', '0006_alter_medicament_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
