# Generated by Django 5.0.4 on 2024-05-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma_app', '0010_alter_agent_genre_alter_medicament_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicament',
            options={'permissions': [('publish_medicament', 'Can publish a Medicine'), ('sell_medicament', 'Can sell a Medicine')]},
        ),
        migrations.AddField(
            model_name='agent',
            name='password',
            field=models.CharField(default=0, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
