# Generated by Django 5.0.4 on 2024-05-21 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharma_app', '0012_alter_medicament_options_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
