# Generated by Django 5.0.4 on 2024-05-21 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharma_app', '0015_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='l_name',
        ),
    ]
